// The quest line. q01 is the tutorial (teaches every core mechanic). Quests
// teach one new thing each, drive the player to catch every species, and gate
// area unlocks at L4 (Cedar Lake) and L8 (Granite Rapids) — matching areas.js.
export const QUESTS = [
  { id: 'q01_first_cast', title: 'First Light at Stillwater', area: 'stillwater', tutorial: true, teaches: 'look, move, charge-cast, set hook, reel in', objectives: [{ type: 'pointer_lock', count: 1 }, { type: 'move', count: 1 }, { type: 'cast', count: 1 }, { type: 'set_hook', count: 1 }, { type: 'land_fish', target: 'any', count: 1 }], rewards: { xp: 40, money: 30 } },
  { id: 'q02_twitch', title: 'Make It Dance', area: 'stillwater', teaches: 'twitch the lure to draw bites', objectives: [{ type: 'twitch', count: 5 }, { type: 'land_fish', target: 'any', count: 1 }], rewards: { xp: 45, money: 25 } },
  { id: 'q03_right_bait', title: 'Right Bait, Right Fish', area: 'stillwater', teaches: 'match gear to species', objectives: [{ type: 'catch_species', target: 'bluegill', count: 1 }, { type: 'catch_species', target: 'pumpkinseed', count: 1 }], rewards: { xp: 55, money: 35 } },
  { id: 'q04_tackle_box', title: 'Pack the Tackle Box', area: 'stillwater', teaches: 'open tackle box, equip a loadout', objectives: [{ type: 'open_tackle_box', count: 1 }, { type: 'equip', count: 1 }, { type: 'land_fish', target: 'any', count: 1 }], rewards: { xp: 50, money: 30 } },
  { id: 'q05_shop', title: 'Spend It at the Shop', area: 'stillwater', teaches: 'money + buying gear', objectives: [{ type: 'open_shop', count: 1 }, { type: 'buy_item', count: 1 }, { type: 'equip', count: 1 }], rewards: { xp: 40, money: 0 } },
  { id: 'q06_bullhead', title: 'Bottom Dwellers', area: 'stillwater', teaches: 'scented bait, dusk/night feeders', objectives: [{ type: 'catch_species', target: 'brown_bullhead', count: 1 }], rewards: { xp: 60, money: 40 } },
  { id: 'q07_bucketmouth', title: 'Bucketmouth', area: 'stillwater', teaches: 'fighting a stronger fish', objectives: [{ type: 'catch_species', target: 'largemouth_pond', count: 1 }, { type: 'land_no_snap', target: 'largemouth_pond', count: 1 }], rewards: { xp: 90, money: 60 } },
  { id: 'q08_stillwater_slam', title: 'Stillwater Slam', area: 'stillwater', teaches: 'area collection', objectives: [{ type: 'catch_species', target: 'bluegill', count: 1 }, { type: 'catch_species', target: 'pumpkinseed', count: 1 }, { type: 'catch_species', target: 'brown_bullhead', count: 1 }, { type: 'catch_species', target: 'largemouth_pond', count: 1 }, { type: 'catch_species', target: 'common_carp', count: 1 }], rewards: { xp: 160, money: 120, unlock: 'stillwater_master' } },
  { id: 'q09_open_map', title: 'Open the Map', area: 'stillwater', teaches: 'level unlock + fast travel', objectives: [{ type: 'reach_level', target: 4, count: 1 }, { type: 'fast_travel', target: 'cedar_lake', count: 1 }], rewards: { xp: 40, money: 50, unlock: 'area_cedar_lake' } },
  { id: 'q10_weed_line', title: 'Working the Weed Line', area: 'cedar_lake', teaches: 'structure + deeper water', objectives: [{ type: 'catch_species', target: 'northern_pike', count: 2 }], rewards: { xp: 120, money: 90 } },
  { id: 'q11_walleye_night', title: 'Eyes in the Dark', area: 'cedar_lake', teaches: 'low-light feeders, jig+minnow', objectives: [{ type: 'catch_species', target: 'walleye', count: 1 }, { type: 'catch_species', target: 'rainbow_trout', count: 1 }], rewards: { xp: 110, money: 90 } },
  { id: 'q12_cedar_census', title: 'Cedar Lake Census', area: 'cedar_lake', teaches: 'second-area collection', objectives: [{ type: 'catch_species', target: 'yellow_perch', count: 1 }, { type: 'catch_species', target: 'crappie', count: 1 }, { type: 'catch_species', target: 'largemouth_bass', count: 1 }, { type: 'catch_species', target: 'northern_pike', count: 1 }, { type: 'catch_species', target: 'channel_catfish', count: 1 }], rewards: { xp: 170, money: 130, unlock: 'cedar_master' } },
  { id: 'q13_trophy', title: 'Trophy on the Line', area: 'cedar_lake', teaches: 'land a trophy, manage drag', objectives: [{ type: 'catch_min_weight', target: 'northern_pike', minWeightKg: 5, count: 1 }], rewards: { xp: 140, money: 140, unlock: 'trophy_net' } },
  { id: 'q14_upriver', title: 'Upriver', area: 'cedar_lake', teaches: 'final unlock + travel', objectives: [{ type: 'reach_level', target: 8, count: 1 }, { type: 'fast_travel', target: 'rapids', count: 1 }], rewards: { xp: 50, money: 70, unlock: 'area_rapids' } },
  { id: 'q15_chrome', title: 'Chrome in Cold Water', area: 'rapids', teaches: 'current seams, acrobatic trout', objectives: [{ type: 'catch_species', target: 'rainbow_trout_river', count: 2 }, { type: 'catch_species', target: 'brook_trout', count: 1 }], rewards: { xp: 140, money: 100 } },
  { id: 'q16_master_angler', title: 'Master Angler', area: 'rapids', teaches: 'apex predator + full mastery', objectives: [{ type: 'catch_species', target: 'smallmouth_bass', count: 1 }, { type: 'catch_species', target: 'brown_trout', count: 1 }, { type: 'catch_species', target: 'muskie', count: 1 }], rewards: { xp: 400, money: 350, unlock: 'master_angler_rod' } },
]

export function questById(id) {
  return QUESTS.find((q) => q.id === id)
}
